source "http://rubygems.org"
source "http://sul-gems.stanford.edu"

group :deployment do
  gem 'capistrano'
  gem 'capistrano-ext'
  gem 'rvm-capistrano'
  gem 'lyberteam-capistrano-devel', '>=1.2.0'
  gem 'net-ssh-krb'
  gem 'gssapi' #, :git => 'git@github.com:cbeer/gssapi.git'
end
